[toolchain]
anchor_version = "1.1.2"

[features]
resolution = true
skip-lint = false

[programs.localnet]
spankwallet = "Bt7jcHC5RE93E6J5HGRtWBBmnXYbC3e21pjXLP6tqtBm"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[hooks]
