[package]
name = "active-defense"
version = "0.1.0"
description = "SpankWallet Active Defense — Poison Token + Malicious Addresses"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "active_defense"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = { version = "1.1.2", features = ["init-if-needed"] }
anchor-spl = "1.1.2"
solana-instructions-sysvar = "3.0.1"
solana-keccak-hasher = "3.1.0"
solana-sha256-hasher = "3.1.0"
